In [38]:
import pandas as pd

In [39]:
df = pd.read_csv('cust_satisfaction.csv')
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  object
 1   Customer Type               103904 non-null  object
 2   Type of Travel              103904 non-null  object
 3   Class                       103904 non-null  object
 4   satisfaction                103904 non-null  object
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB

In [41]:
df.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [42]:
df.dropna(inplace=True)

In [43]:
df.duplicated().sum()

np.int64(172)

In [44]:
df.drop_duplicates(inplace=True)

In [45]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [46]:
df['Gender'] = df['Gender'].map({'Male': 1,'Female' : 0})
df['Customer Type'] = df['Customer Type'].map({'Loyal Customer': 1, 'disloyal Customer': 0})
df['Type of Travel'] = df['Type of Travel'].map({'Business travel': 1, 'Personal Travel': 0})
df['Class'] = df['Class'].map({'Eco': 0, 'Eco Plus': 1, 'Business': 2})
df['satisfaction'] = df['satisfaction'].map({'satisfied': 1, 'neutral or dissatisfied': 0})
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,1,0,1,0,13,460,5,4,5,25,18.0
1,1,0,1,2,0,25,235,1,3,1,1,6.0
2,0,1,1,2,1,26,1142,5,4,5,0,0.0
3,0,1,1,2,0,25,562,2,3,2,11,9.0
4,1,1,1,2,1,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,0,0,1,0,0,23,192,2,4,2,3,0.0
103900,1,1,1,2,1,49,2347,5,5,4,0,0.0
103901,1,0,1,2,0,30,1995,4,4,4,7,14.0
103902,0,0,1,0,0,22,1000,1,1,1,0,0.0
103903,1,1,1,2,0,27,1723,1,4,1,0,0.0

In [47]:
loyal_customer = df[df['Customer Type'] == 1].loc[0:20000]
disloyal_customer = df[df['Customer Type'] == 0]

In [48]:
loyal_customer

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,1,0,1,0,13,460,5,4,5,25,18.0
2,0,1,1,2,1,26,1142,5,4,5,0,0.0
3,0,1,1,2,0,25,562,2,3,2,11,9.0
4,1,1,1,2,1,61,214,3,4,3,0,0.0
5,0,1,0,0,0,26,1180,1,4,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
19994,1,1,1,1,0,29,1363,1,3,1,160,154.0
19995,0,1,1,2,1,29,259,5,4,5,0,2.0
19997,0,1,1,2,1,63,2987,4,4,3,0,9.0
19999,0,1,1,2,1,49,2585,5,5,3,0,0.0
20000,1,1,1,2,0,63,1639,4,4,4,0,0.0

In [49]:
new_data = pd.concat([loyal_customer,disloyal_customer],axis = 0)
new_data

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,1,0,1,0,13,460,5,4,5,25,18.0
2,0,1,1,2,1,26,1142,5,4,5,0,0.0
3,0,1,1,2,0,25,562,2,3,2,11,9.0
4,1,1,1,2,1,61,214,3,4,3,0,0.0
5,0,1,0,0,0,26,1180,1,4,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103892,0,0,1,2,0,37,596,3,3,3,110,121.0
103895,0,0,1,0,0,24,1055,1,5,1,13,10.0
103899,0,0,1,0,0,23,192,2,4,2,3,0.0
103901,1,0,1,2,0,30,1995,4,4,4,7,14.0
103902,0,0,1,0,0,22,1000,1,1,1,0,0.0

In [50]:
x = new_data.drop('Customer Type',axis=1)
y = new_data[['Customer Type']]

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # mean = 0 and sd = 1
x_train_scaled = sc.fit_transform(x_train)
# fit == learns the parameter
# transform -- convert the data
x_test_scaled = sc.transform(x_test)